import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

const sansFont = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={sansFont.className}>{children}</body>
        </html>
    );
}
